'use client';
import {useState} from 'react';
import {HEROES,SKILLS,ARTIFACTS,fmt,cost,tapDamage,heroDps,evolveCost,artifactCost,skillCost,skillDuration,skillCooldown,skillPower,relicGain,weaponSets,achievementProgress, type State,type Action} from '../lib/engine';
import {SLOTS,RARITIES,DAILY_TASKS,ACHIEVEMENTS,MONSTERS,REGIONS,PERKS} from '../lib/content';
type Props={s:State;tab:string;ready:boolean;basePath:string;act:(a:Omit<Action,'at'>)=>void;onPrestige:()=>void};
export function MonsterSprite({id,basePath,className=''}:{id:number;basePath:string;className?:string}){const monster=MONSTERS[id%60];return <span role="img" aria-label={monster.name} className={`atlas-sprite ${className}`} style={{backgroundImage:`url("${basePath}${monster.sheet?`monsters-${monster.sheet+1}.webp`:'monsters-atlas.webp'}")`,backgroundPosition:`${monster.sprite%4/3*100}% ${Math.floor(monster.sprite/4)/2*100}%`,filter:`hue-rotate(${monster.variant*48}deg)`}}/>;}
function amountFor(s:State,i:number,qty:number){if(qty)return qty;let lo=0,hi=Math.min(1000,2000-(i<0?s.level:s.heroes[i]));while(lo<hi){const mid=Math.ceil((lo+hi)/2);if(cost(s,i,mid)<=s.gold)lo=mid;else hi=mid-1;}return lo;}
export default function GameContent({s,tab,ready,basePath,act,onPrestige}:Props){
 const [qty,setQty]=useState(1),[filter,setFilter]=useState(''),[detail,setDetail]=useState(-1),[collection,setCollection]=useState('monsters'),[confirm,setConfirm]=useState(-1);
 const action=(a:Omit<Action,'at'>)=>{if(ready)act(a);};
 const masterCount=amountFor(s,-1,qty);
 return <fieldset className="content-fieldset" disabled={!ready}>
 {tab==='heroes'?<><div className="buy-toolbar"><span>升級數量</span><div>{[1,10,25,100,0].map(n=><button key={n} className={qty===n?'chosen':''} onClick={()=>setQty(n)}>{n?`×${n}`:'MAX'}</button>)}</div></div>
 <div className="sword-master"><div className="hero-top"><span className="avatar master">⚔️</span><div><h3>劍術大師 <span>你</span></h3><p>{s.world?'法師世界':'劍士世界'}</p></div><b>Lv. {s.level}</b></div><div className="master-bottom"><span>點擊傷害<strong>{fmt(tapDamage(s))}</strong></span><button className="buy-button" disabled={!masterCount||s.gold<cost(s,-1,masterCount)||s.level+masterCount>2000} onClick={()=>action({type:'upgrade',amount:qty})}>升級 +{masterCount}<small>● {fmt(cost(s,-1,masterCount))}</small></button></div></div>
 <div className="list-heading"><h3>英雄夥伴</h3><span>{s.heroes.filter(n=>n>0).length} / 33 已招募</span></div><p className="panel-note">點選英雄查看被動、進化及武器。每 25 級傷害加倍，每 50 級解鎖團隊加成。</p>
 <div className="hero-list">{HEROES.map((h,i)=>{const count=amountFor(s,i,qty),injured=s.wounded[i]>s.last;return <div className="hero-entry" key={h.name}><div className={`hero-card ${s.heroes[i]===0?'unhired':''}`}><button className={`avatar hero-${i%4}`} aria-label={`查看${h.name}`} onClick={()=>setDetail(detail===i?-1:i)}>{h.icon}</button><div className="hero-info"><button onClick={()=>setDetail(detail===i?-1:i)}><h3>{h.name}<small>Lv. {s.heroes[i]} {s.evolutions[i]>0?`★${s.evolutions[i]}`:''}</small></h3></button><p>{h.title}</p><span>{injured?`負傷 ${Math.ceil((s.wounded[i]-s.last)/1000)}s`:`⚡ ${fmt(heroDps(s,i))} DPS`}</span></div><button className="buy-button" disabled={!count||s.gold<cost(s,i,count)||s.heroes[i]+count>2000} onClick={()=>action({type:'hero',index:i,amount:qty})}>{s.heroes[i]?'升級':'招募'} +{count}<small>● {fmt(cost(s,i,count))}</small></button></div>{detail===i&&<div className="hero-details"><p>武器強化 Lv.{s.weapons[i]} · 永久保留</p><p>每 50 級：團隊{['點擊傷害','英雄傷害','金幣獲得'][i%3]} +2%<br/>目前提供 +{Math.floor(s.heroes[i]/50)*2}%</p><p>進化需求：Lv.100；重回 Lv.1，基礎傷害 ×10,000，最多 10 次。轉生會重置进化。</p><button className="buy-button" disabled={s.heroes[i]<100||s.evolutions[i]>=10||s.gold<evolveCost(s,i)} onClick={()=>action({type:'evolve',index:i})}>進化 ★{s.evolutions[i]+1} · ● {fmt(evolveCost(s,i))}</button>{injured&&<button className="outline-button" disabled={s.diamonds<5} onClick={()=>action({type:'revive',index:i})}>立即復甦 · 💎5</button>}</div>}</div>;})}</div></>
 :tab==='artifacts'?<><div className="intro-card"><span className="large-symbol">💠</span><h3>跨越輪迴的力量</h3><p>收集 {s.artifacts.filter(n=>n>0).length} / 30 件 · ◆ {fmt(s.relics)} 聖物</p></div><input className="content-search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="搜尋神器名稱或加成" aria-label="搜尋神器"/>{ARTIFACTS.map((a,i)=>({a,i})).filter(({a})=>(a.name+a.desc).includes(filter)).map(({a,i})=><div className="artifact-card" key={a.name}><span>{a.icon}</span><h3>{a.name}<small> Lv.{s.artifacts[i]} / {a.max}</small></h3><p>{a.desc}</p><button className="buy-button" disabled={s.relics<artifactCost(s,i)||s.artifacts[i]>=a.max} onClick={()=>action({type:'artifact',index:i})}>{s.artifacts[i]>=a.max?'已達上限':s.artifacts[i]?'強化神器':'發現神器'} · ◆ {artifactCost(s,i)}</button>{s.artifacts[i]>0&&<button className="text-link" onClick={()=>setConfirm(confirm===i?-1:i)}>重鑄神器</button>}{confirm===i&&<div className="inline-confirm"><p>花費 20 鑽石，清除此神器等級，返還 {Math.floor(s.artifactSpent[i]*.5)} 聖物（投入的 50%）。</p><button className="outline-button" disabled={s.diamonds<20} onClick={()=>{action({type:'artifactSalvage',index:i});setConfirm(-1);}}>確認重鑄</button><button onClick={()=>setConfirm(-1)}>取消</button></div>}</div>)}</>
 :tab==='skills'?<><div className="content-heading"><h3>主動技能</h3><p>用金幣提升到 Lv.10。技能等級隨轉生重置。</p></div>{SKILLS.map((k,i)=>{const locked=s.level<k.level,cd=Math.max(0,Math.ceil((s.cooldowns[i]-s.last)/1000));return <article className="feature-card" key={k.name}><div className="feature-title"><span>{k.icon}</span><h3>{k.name}<small>Lv. {s.skillLevels[i]} / 10</small></h3></div><p>{k.desc}</p><div className="mini-stats"><span>威力 ×{skillPower(s,i).toFixed(2)}</span><span>持續 {skillDuration(s,i).toFixed(0)}s</span><span>冷卻 {skillCooldown(s,i).toFixed(0)}s</span></div><div className="feature-actions"><button className="buy-button" disabled={locked||s.skillLevels[i]>=10||s.gold<skillCost(s,i)} onClick={()=>action({type:'skillUp',index:i})}>強化 · ●{fmt(skillCost(s,i))}</button><button className="outline-button" disabled={locked||cd>0} onClick={()=>action({type:'skill',index:i})}>{locked?`劍士 Lv.${k.level} 解鎖`:cd?`${cd}s`:'施放'}</button></div></article>;})}<p className="panel-note">冷卻時間與技能持續時間還可透過神器永久改善。</p></>
 :tab==='equipment'?<><div className="content-heading"><h3>冒險者裝備</h3><p>每擊敗 3 位頭目掉落裝備，也可從地下城、簽到及試煉獲得。</p></div><div className="equipment-slots">{SLOTS.map((slot,i)=>{const g=s.gear.find(g=>g.id===s.equipped[i]);return <div key={slot.name} className={`rarity-${g?.rarity??0}`}><span>{slot.icon}</span><b>{slot.name}</b><small>{g?`+${(g.power*100).toFixed(1)}%`:'未裝備'}</small></div>;})}</div><div className="list-heading"><h3>背包 {s.gear.length} / 100</h3><span>✧ {s.dust} 星塵</span></div><button className="outline-button full-width" disabled={s.dust<50||s.gear.length>=100} onClick={()=>action({type:'craft'})}>鍛造史詩以上裝備 · ✧50</button>{!s.gear.length&&<div className="empty-state">第一件裝備在第 15 關頭目後掉落。強化劍士與英雄，向更深的關卡前進。</div>}{[...s.gear].sort((a,b)=>b.rarity-a.rarity||b.power-a.power).map(g=><article key={g.id} className={`gear-card rarity-${g.rarity}`}><span>{SLOTS[g.slot].icon}</span><div><h3>{RARITIES[g.rarity]}{SLOTS[g.slot].name}<small>Lv.{g.level}</small></h3><p>{['點擊傷害','英雄傷害','金幣獲得','所有傷害','暴擊倍率'][g.slot]} +{(g.power*100).toFixed(1)}%</p><div className="feature-actions"><button className="buy-button" disabled={s.equipped.includes(g.id)} onClick={()=>action({type:'equip',index:g.id})}>{s.equipped.includes(g.id)?'已裝備':'裝備'}</button><button className="outline-button" disabled={s.equipped.includes(g.id)} onClick={()=>action({type:'salvage',index:g.id})}>分解 +{5*(g.rarity+1)}✧</button></div></div></article>)}<p className="panel-note">裝備與星塵不會因轉生消失。滿背包後掉落物自動轉成星塵。分解後無法復原。</p></>
 :tab==='adventure'?<><div className="content-heading"><h3>每日遠征</h3><p>每日任務以 UTC 00:00 重置。今日鑽石、武器與装備等你帶回。</p></div><article className="feature-card login-card"><div className="feature-title"><span>🎁</span><h3>每日簽到<small>連續 {s.streak} 天</small></h3></div><p>每日 15–45 鑽石，第 7 天額外史詩裝備與英雄武器。</p><button className="buy-button" disabled={s.daily.login} onClick={()=>action({type:'daily'})}>{s.daily.login?'今日已簽到':'領取今日禮物'}</button></article>
 <h3 className="subheading">每日任務</h3>{DAILY_TASKS.map((q,i)=><div className="quest-card" key={q.name}><div><b>{q.name}</b><small>{Math.min(q.target,s.daily[q.metric])} / {q.target}</small><progress max={q.target} value={s.daily[q.metric]}/></div><button className="buy-button" disabled={s.daily.claimed.includes(i)||s.daily[q.metric]<q.target} onClick={()=>action({type:'quest',index:i})}>{s.daily.claimed.includes(i)?'已領取':`💎 ${q.reward}`}</button></div>)}
 <h3 className="subheading">每日地下城</h3><p className="panel-note">60 秒擊敗 10 波。每個難度每日可領一次：鑽石、英雄武器、裝備。挑戰中主線暫停，失敗可以重試。</p>{['遺跡探索','精英狩獵','深淵討伐'].map((n,i)=><article className="feature-card" key={n}><div className="feature-title"><span>{['🏛️','⚔️','🌋'][i]}</span><h3>{n}<small>難度 {i+1} · 💎{20*(i+1)}</small></h3></div><button className="buy-button" disabled={s.best<5||!!s.trial||s.daily.dungeons.includes(i)} onClick={()=>action({type:'trial',index:i})}>{s.daily.dungeons.includes(i)?'今日已通關':s.best<5?'第 5 關解鎖':'進入地下城'}</button></article>)}
 <h3 className="subheading">本週極限試煉</h3><p className="panel-note">轉生一次後解鎖。120 秒生存挑戰，本週最佳 {s.weekly.best} 隻。這是個人挑戰，不是連線錦標賽；每週一 UTC 重置。</p><button className="primary-button" disabled={!!s.trial||s.prestiges<1} onClick={()=>action({type:'trial',index:3})}>{s.prestiges<1?'轉生一次解鎖':'開始本週試煉'}</button>{[5,10,20].map((n,i)=><div className="quest-card" key={n}><span>擊敗 {n} 隻<br/><small>💎{[30,60,100][i]} ＋武器／裝備</small></span><button className="buy-button" disabled={s.weekly.best<n||s.weekly.claimed.includes(i)} onClick={()=>action({type:'trialReward',index:i})}>{s.weekly.claimed.includes(i)?'已領取':'領取'}</button></div>)}{s.trial&&<button className="outline-button full-width" onClick={()=>action({type:'leaveTrial'})}>退出目前挑戰</button>}</>
 :tab==='collection'?<><div className="collection-tabs">{[['monsters','怪物'],['weapons','武器'],['achievements','成就'],['worlds','世界']].map(([id,label])=><button key={id} className={collection===id?'chosen':''} onClick={()=>setCollection(id)}>{label}</button>)}</div>
 {collection==='monsters'?<><div className="content-heading"><h3>巨獸圖鑑 · {s.seen.length} / 60</h3><p>60 種不同造型的巨獸。遭遇即可記錄；寶箱怪在第 10 關後有額外金幣。</p></div><div className="bestiary-grid">{MONSTERS.map(m=><article key={m.id} className={s.seen.includes(m.id)?'':'undiscovered'}><MonsterSprite id={m.id} basePath={basePath}/><h3>{s.seen.includes(m.id)?m.name:'尚未遭遇'}</h3><small>NO.{String(m.id+1).padStart(2,'0')} {m.id===7?'金幣寶箱':''}</small></article>)}</div></>
 :collection==='weapons'?<><div className="content-heading"><h3>英雄武器庫</h3><p>收集 {s.weapons.filter(n=>n>0).length} / 33 · 完整套裝 {weaponSets(s)} 套</p><p>每件武器為該英雄提供 +50% 傷害；每套完整武器額外全隊 +900%。轉生保留。</p></div>{HEROES.map((h,i)=><div className="weapon-row" key={h.name}><span>{h.icon}</span><div><b>{h.name}</b><small>{h.title}</small></div><strong>武器 Lv.{s.weapons[i]}</strong></div>)}</>
 :collection==='achievements'?<><div className="content-heading"><h3>冒險成就 · {s.achievements.length} / {ACHIEVEMENTS.length}</h3><p>成就永久保留，每項獎勵限領一次。</p></div>{ACHIEVEMENTS.map((a,i)=><div className="quest-card" key={a.name}><div><b>{a.name}</b><small>{fmt(Math.min(a.target,achievementProgress(s,i)))} / {fmt(a.target)}</small><progress value={achievementProgress(s,i)} max={a.target}/></div><button className="buy-button" disabled={s.achievements.includes(i)||achievementProgress(s,i)<a.target} onClick={()=>action({type:'achievement',index:i})}>{s.achievements.includes(i)?'已領取':`💎${a.reward}`}</button></div>)}</>
 :<><div className="content-heading"><h3>十境遠征</h3><p>每 20 關換一個場景，每 200 關進入下一輪遠征。</p></div><div className="world-gallery">{REGIONS.map((name,i)=><div key={name}><span className="world-thumbnail" style={{backgroundImage:`url("${basePath}worlds-atlas.webp")`,backgroundPosition:`${i%5/4*100}% ${Math.floor(i/5)*100}%`}}/><b>{name}</b><small>第 {i*20+1}–{i*20+20} 關</small></div>)}</div><article className="feature-card"><h3>法師世界</h3><p>最高達第 300 關並轉生 5 次後可切換。巨獸生命 ×25、金幣 ×10、轉生聖物 ×2。切換從第 1 關開始，隊伍與收集品保留。</p><p>劍士世界最高 {s.worldBest[0]} 關<br/>法師世界最高 {s.worldBest[1]} 關</p><button className="buy-button" disabled={s.best<300||s.prestiges<5||!!s.trial} onClick={()=>action({type:'world',index:s.world?0:1})}>前往{s.world?'劍士':'法師'}世界</button></article></>}
 </>
 :tab==='shop'?<><div className="content-heading"><h3>旅人商店</h3><p>💎 {fmt(s.diamonds)} 鑽石</p><p>鑽石從遊戲內任務、成就、地下城獲得，沒有付費購買。</p></div>{PERKS.map((p,i)=><article className="feature-card" key={p.name}><div className="feature-title"><span>{p.icon}</span><h3>{p.name}</h3></div><p>{p.desc}</p><button className="buy-button" disabled={s.diamonds<p.price||(i===3&&!!s.trial)} onClick={()=>action({type:'perk',index:i})}>購買並使用 · 💎{p.price}</button></article>)}<h3 className="subheading">最近獲得</h3>{s.log.length?s.log.map((entry,i)=><p className="event-log" key={i}>{entry}</p>):<p className="empty-state">你的冒險故事即將開始。</p>}</>
 :<div className="prestige-card"><div className="prestige-orb">✦</div><div className="eyebrow">A NEW BEGINNING</div><h2>重生，成為傳說</h2><p>第 50 關開啟轉生。重置關卡、金幣、劍士／英雄等級、英雄進化與技能等級。保留神器、裝備、英雄武器、鑽石、任務、成就與圖鑑。</p><div className="prestige-reward"><span>本次轉生可獲得</span><strong>◆ {relicGain(s)}</strong><small>聖物</small></div><button className="primary-button" disabled={!relicGain(s)||!!s.trial} onClick={onPrestige}>開啟轉生</button><p>{s.stage<50?`距離轉生還有 ${50-s.stage} 關`:'投資神器，開啟下一段更強的遠征。'}</p><p>第 300 關、5 次轉生：解鎖法師世界。</p></div>}
 </fieldset>;
}
