'use client';
import {useState} from 'react';
import {playerMilestone,nextPlayerMilestone} from '../lib/tt2-player';
import {petAttackDamage,MANA_DEFAULTS} from '../lib/engine';
import {compare,fromNumber,fromText,toNumber,ratio} from '../lib/big-number';
import {heroSkills,heroSkillValue,heroPowerBoost,PENDING_HERO_EFFECTS} from '../lib/tt2-hero-passives';
import {petRequiredTaps} from '../lib/tt2-pet-combat';
import {RESOURCE_PERKS,perkLevel,perkLimit,perkValue} from '../lib/tt2-perks';
import {PET_NAMES,TALENT_NAMES,SET_NAMES,RARITY_NAMES} from '../lib/zh-tw';
import {SKILL_TEXT} from '../lib/tt2-skill-text';
import {TT2_PETS,TT2_GEAR,TT2_DAILY} from '../lib/tt2-data';
import {petBonus,equipmentEffect} from '../lib/tt2-rules';
import {craftPrice,EGG_INTERVAL} from '../lib/tt2-collection';
import {TT2_ACHIEVEMENTS,TT2_DAILY_TASKS,ACHIEVEMENT_PANEL_TEXT,UNMEASURED_ACHIEVEMENTS,UNMEASURED_DAILY_TASKS,DAILY_TASK_PAID,achievementTier,achievementClaimed,achievementReward,achievementProgress,dailyTaskAvailable,dailyTaskProgress,dailyTaskDone,dailyTaskClaimed} from '../lib/engine';
import {HEROES,SKILLS,SKILL_ORDER,SKILL_DATA,heroLevel,cost,swordMasterBaseDamage,fmt,tapDamage,dps,skillPower,skillCost,skillMana,skillDuration,skillCooldown,manaMax,manaRegen,relicGain,artifactCost,buildDamage,type State,type Action} from '../lib/engine';
import {TT2_ARTIFACTS,TT2_TREE,TT2_SETS,artifactValue,discoveryCost,canDiscover,canBuyTalent,spentPoints,effectLabel,bonusDefinitions,effectText,BUILD_COEFFICIENTS,type Build} from '../lib/tt2-rules';
type Props={s:State;tab:string;ready:boolean;basePath:string;act:(a:Omit<Action,'at'>)=>void;onPrestige:()=>void};
const branches=['Knight','Pet','Warlord','Sorcerer','Rogue','Alchemist'];
const branchNames=['騎士','召喚師','督軍','術士','盜賊','煉金術士'];
const builds:[Build,string][]=[['tap','手動點擊'],['pet','寵物'],['ship','公會飛船'],['clone','影分身'],['dagger','匕首'],['heavenly','天堂'],['goldGun','金槍']];
export default function TT2Panels({s,tab,ready,basePath,act,onPrestige}:Props){
 const [qty,setQty]=useState(1),[search,setSearch]=useState(''),[branch,setBranch]=useState('Knight'),[selected,setSelected]=useState<Build>('clone'),[detail,setDetail]=useState(-1),[collection,setCollection]=useState('pets');
 const t=s.tt2!,powerBoost=heroPowerBoost(t),nextMilestone=nextPlayerMilestone(s.level);
 const price=(i:number)=>cost(s,i,qty||1);
 const priceText=(i:number)=>{const p=price(i);return p.e<4?toNumber(p).toLocaleString('zh-TW',{maximumFractionDigits:2}):fmt(p);};
 return <fieldset className="content-fieldset" disabled={!ready}>
 <p className="panel-note">點擊泰坦二代 7.5 規則校正版 · <a href={`${basePath}rules.html`} target="_blank" rel="noreferrer">已還原／仍待完成 ↗</a></p>
 {tab==='heroes'?<>
  <div className="buy-toolbar"><span>升級數量</span><div>{[1,10,25,100,0].map(n=><button key={n} className={qty===n?'chosen':''} onClick={()=>setQty(n)}>{n?`×${n}`:'最多'}</button>)}</div></div>
  <div className="sword-master"><div className="hero-top"><span className="avatar master">⚔️</span><div><h3>劍術大師</h3><p>等級 {s.level} · 點擊 {fmt(tapDamage(s))}</p><p>基礎劍傷 {fmt(swordMasterBaseDamage(s))}</p><p>里程碑累計 ×{fmt(playerMilestone(s.level))}</p><p>{nextMilestone?`下一里程碑：等級 ${nextMilestone.level} · 累計 ×${fmt(fromText(nextMilestone.total))}`:'已達本版等級上限'}</p></div><button className="buy-button" disabled={s.level>=2000||s.gold<price(-1)} onClick={()=>act({type:'upgrade',amount:qty})}>升級<small>●{priceText(-1)}{qty===0?' 起':''}</small></button></div></div>
  <div className="list-heading"><h3>英雄 {HEROES.filter((_,i)=>heroLevel(s,i)>0).length} / {HEROES.length}</h3><span>總每秒傷害 {fmt(dps(s))}</span></div>
  <p className="panel-note">英雄名稱、初始價格及初始傷害依二代資料表。等級里程碑、基礎被動與戰術洞察已接入；英雄轉點擊、十倍金幣機率、米達斯之心與多重泰坦金源、卷軸增幅、逐級成長與昇華仍待還原。</p>
  {HEROES.map((h,i)=><div className="hero-card" key={h.name}><span className={`avatar hero-${i%4}`}>{h.icon}</span><div className="hero-info"><h3>{h.name}<small>等級 {heroLevel(s,i)}</small></h3><p>{({Melee:'近戰',Ranged:'遠程',Spell:'咒術'} as Record<string,string>)[h.title]||h.title}</p><details><summary>等級被動 · 已解鎖 {heroSkills(i).filter(k=>k.level<=heroLevel(s,i)&&!PENDING_HERO_EFFECTS.has(k.effect)).length} 項</summary>{heroSkills(i).map(k=><p key={k.id}>等級 {k.level} · {k.effect==='Goldx10Chance'?'十倍金幣機率':effectLabel(k.effect)} {effectText(k.effect,heroSkillValue(k,powerBoost))} · {PENDING_HERO_EFFECTS.has(k.effect)?'待還原':k.level>2000?'待開放昇階':heroLevel(s,i)>=k.level?'已生效':'未解鎖'}</p>)}</details></div><button className="buy-button" disabled={heroLevel(s,i)>=2000||s.gold<price(i)} onClick={()=>act({type:'hero',index:i,amount:qty})}>{heroLevel(s,i)?'升級':'招募'}<small>●{priceText(i)}{qty===0?' 起':''}</small></button></div>)}
 </>:tab==='artifacts'?<>
  <div className="intro-card"><span className="large-symbol">💠</span><h3>神器</h3><p>{t.artifacts.filter(n=>n>0).length} / 103 · ◆{fmt(s.relics)} 聖物</p><button className="buy-button" disabled={s.best<60||!canDiscover(t)||s.relics<discoveryCost(t)} onClick={()=>act({type:'discover'})}>{s.best<60?'第 60 關開放':canDiscover(t)?`隨機發現 · ◆${fmt(discoveryCost(t))}`:'神器已收齊'}</button></div>
  <p className="panel-note">傷害與效果分開計算；只增強指定流派、金源或裝備。涉及尚未完成系統的神器，會保留數值但尚無對應收益。附魔與拆解暫未開放。</p>
  <input className="content-search" aria-label="搜尋神器" placeholder="搜尋神器名稱或效果" value={search} onChange={e=>setSearch(e.target.value)}/>
  {TT2_ARTIFACTS.map((a,i)=>({a,i})).filter(({a})=>(a.name+a.english+effectLabel(a.effect)).toLowerCase().includes(search.toLowerCase())).map(({a,i})=><article className="artifact-card" key={a.id}><span>💠</span><h3>{a.name}<small>等級 {t.artifacts[i]}{a.max?` / ${a.max}`:''}</small></h3><p>{effectLabel(a.effect)}</p><p>目前效果 {effectText(a.effect,artifactValue(t,i))} · 神器傷害 +{fmt(a.damage*t.artifacts[i]*100)}%</p><button className="buy-button" disabled={!t.artifacts[i]||!!a.max&&t.artifacts[i]>=a.max||s.relics<artifactCost(s,i)} onClick={()=>act({type:'artifact',index:i})}>{!t.artifacts[i]?'尚未取得':a.max&&t.artifacts[i]>=a.max?'已滿級':`升級 · ◆${fmt(artifactCost(s,i))}`}</button><button className="text-link" onClick={()=>setDetail(detail===i?-1:i)}>數值來源與效果</button>{detail===i&&<p className="panel-note">版本 7.5.0 · 效果係數 {a.value}，成長指數 {a.exponent}。{a.max?'有等級上限':'無原版等級上限；本網頁暫設數值保護上限 100 萬級'}。{a.enchant>0?'此神器有附魔資料，尚未實作附魔流程。':''}</p>}</article>)}
 </>:tab==='skills'?<>
  <div className="content-heading"><h3>主動技能與魔力</h3><p>{manaMax(s)>0?`魔力 ${s.tt2!.mana.toFixed(1)} / ${manaMax(s).toFixed(0)} · 每分鐘回復 ${(manaRegen(s)*60).toFixed(1)}`:`魔力上限依已解鎖的主動技能計算，每個 ${MANA_DEFAULTS.capPerSkill} 點；第一個技能在劍術大師 ${SKILLS.reduce((low,k)=>Math.min(low,k.level),Infinity)} 級解鎖`}</p></div>
  {SKILL_ORDER.map(i=>{const k=SKILLS[i],cd=Math.max(0,Math.ceil((s.cooldowns[i]-s.last)/1000));return <article className="feature-card" key={k.name}><div className="feature-title"><span>{k.icon}</span><h3>{k.name}<small>等級 {s.skillLevels[i]} / {SKILL_DATA[i].max}</small></h3></div><p>{(SKILL_TEXT[SKILL_DATA[i].id]?.quick??'').replace('{0}',fmt(skillPower(s,i)))}</p><p className="panel-note">{k.desc}</p><div className="mini-stats"><span>消耗 {skillMana(s,i).toFixed(0)} 魔力</span><span>{skillDuration(s,i).toFixed(0)} 秒</span><span>冷卻 {skillCooldown(s,i).toFixed(1)} 秒</span></div><div className="feature-actions"><button className="buy-button" disabled={s.level<k.level||s.skillLevels[i]>=SKILL_DATA[i].max||compare(s.gold,fromNumber(skillCost(s,i)))<0} onClick={()=>act({type:'skillUp',index:i})}>升級 · ●{fmt(skillCost(s,i))}</button><button className="outline-button" disabled={!s.skillLevels[i]||s.level<k.level||!!cd||t.mana<skillMana(s,i)} onClick={()=>act({type:'skill',index:i})}>{s.level<k.level?`劍士 等級 ${k.level}`:cd?`${cd} 秒`:t.mana<skillMana(s,i)?'魔力不足':'施放'}</button></div></article>;})}
  <p className="panel-note">基礎六技能採逐級表。多重施法與流派專屬額外法術尚待完成。</p>
 </>:tab==='adventure'?<>
  <div className="content-heading"><h3>技能樹</h3><p>可用 {t.points} 點 · 已分配 {spentPoints(t)} 點</p></div>
  <div className="collection-tabs">{branches.map((b,i)=><button key={b} className={branch===b?'chosen':''} onClick={()=>setBranch(b)}>{branchNames[i]}</button>)}</div>
  <p className="panel-note">費用、前置條件與等級效果來自 7.5 資料。傷害、金幣與魔力加成已連接；跳關、連擊操作、公會、寵物等特殊行為仍待完成，勿將資料表視為所有行為已還原。</p>
  {TT2_TREE.map((k,i)=>({k,i})).filter(({k})=>k.branch===branch).map(({k,i})=><article className="feature-card" key={k.id}><h3>{TALENT_NAMES[k.name]}<small>等級 {t.tree[i]} / {k.max}</small></h3>{k.effects.map(e=><p key={e.type}>{effectLabel(e.type)}：{t.tree[i]?fmt(e.values[t.tree[i]]):'未啟用'}</p>)}<small>本樹累計 {k.required} 點 · 前置 {k.prerequisite==='None'?'無':TALENT_NAMES[TT2_TREE.find(n=>n.id===k.prerequisite)?.name||'']}</small><button className="buy-button" disabled={!canBuyTalent(t,i,s.best)} onClick={()=>act({type:'talent',index:i})}>{t.tree[i]>=k.max?'已滿級':`升級 · ${k.cost[t.tree[i]]} 點`}</button></article>)}
  <button className="outline-button full-width" disabled={!spentPoints(t)} onClick={()=>act({type:'resetTalents'})}>返還技能點（網頁版暫時免費）</button>
 </>:tab==='equipment'?<>
  <div className="content-heading"><h3>裝備 · {t.inventory.length} / 100</h3><p>劍、頭盔、衣服、靈氣、砍痕 · 工藝碎片 {t.shards}</p></div>
  <p className="panel-note">首次通過第 16 關後每 20 關掉落。主屬性採原版公式；掉落等級與品質分布暫為網頁近似，副屬性待還原。集齊套裝後，丟棄裝備仍保留收藏。</p>
  {!t.inventory.length&&<p>尚無裝備，繼續推進關卡或領取登入獎勵。</p>}
  {t.inventory.map(item=>{const g=TT2_GEAR[item.definition],equipped=t.equipped[g.slot]===item.id;return <article className="feature-card" key={item.id}><h3>{['⚔️ 劍','🪖 頭盔','🥋 衣服','🔮 靈氣','✨ 砍痕'][g.slot]} · 等級 {item.level}</h3><small>{SET_NAMES[g.set]||'一般裝備'} · {g.limited?'活動':({1:'一般',2:'稀有',3:'傳說',4:'神話',5:'獨特'} as Record<number,string>)[g.rarity]||'特殊'} · 編號 {item.id}</small><p>{effectLabel(g.effect)} {effectText(g.effect,equipmentEffect(t,item))}</p><div className="feature-actions"><button className="buy-button" disabled={equipped} onClick={()=>act({type:'equip',index:item.id})}>{equipped?'已裝備':'裝備'}</button><button className="outline-button" disabled={equipped} onClick={()=>act({type:'gearDiscard',index:item.id})}>丟棄</button></div></article>;})}
  {!!s.gear.length&&<details><summary>舊版封存裝備 {s.gear.length} 件</summary>{s.gear.map(g=><p key={g.id}>#{g.id} · 原部位 {g.slot+1} · 原效果 {g.power.toFixed(3)}</p>)}</details>}
 </>:tab==='collection'?<>
  <div className="collection-tabs">{[['pets','寵物'],['sets','套裝'],['achievements','成就'],['builds','流派係數']].map(([id,label])=><button key={id} className={collection===id?'chosen':''} onClick={()=>setCollection(id)}>{label}</button>)}</div>
  {collection==='pets'?<><div className="content-heading"><h3>寵物 {t.petLevels.filter(n=>n>0).length} / 30</h3><p>傷害與支援各可出戰一隻。未出戰每 5 級增加 5% 被動效果，100 級達完整效果。</p><p>每 {petRequiredTaps(t)} 次有效點擊發動寵物攻擊 · 目前傷害 {fmt(petAttackDamage(s))} · 累計攻擊 {t.petAttacks} 次</p></div><button className="buy-button" disabled={!t.eggs} onClick={()=>act({type:'egg'})}>開啟寵物蛋 · {t.eggs} / 2</button><p className="panel-note">每 4 小時補充一顆，上限兩顆。下顆 {t.eggs===2?'已滿':`${Math.max(0,Math.ceil((t.eggAt+EGG_INTERVAL-s.last)/60000))} 分鐘`}。目前每顆給 1 級；原版多級機率、自動攻擊、閃電爆發與閃光突進尚待還原。</p>{TT2_PETS.map((p,i)=><article className="feature-card" key={p.id}><h3>{PET_NAMES[p.name]}<small>等級 {t.petLevels[i]}</small></h3><p>{p.family==='Legacy'?'傳統':'異國'} · {p.slot==='Damage'?'傷害':'支援'}</p><p>{effectLabel(p.effect)} {effectText(p.effect,petBonus(t,i))}</p><button className="buy-button" disabled={!t.petLevels[i]||t.activePets.includes(i)} onClick={()=>act({type:'petEquip',index:i})}>{t.activePets.includes(i)?'出戰中':t.petLevels[i]?'出戰':`第 ${p.unlock} 關加入蛋池`}</button></article>)}</>
  :collection==='sets'?<><h3>套裝效果資料 · {TT2_SETS.length} 組</h3><p className="panel-note">已收齊套裝會標示完成。可使用碎片依序製作缺少部位。基礎數值加成已接入；工藝力量、每日成長與特殊行為仍待還原。</p>{TT2_SETS.map((set,i)=><article className="feature-card" key={set.id}><h3>{SET_NAMES[set.id]}<small>{RARITY_NAMES[set.rarity]} · {t.sets.includes(i)?'已收齊':`${t.pieces.filter(p=>p.set===i).length} / 5`}</small></h3>{set.effects.map(e=><p key={e.type}>{effectLabel(e.type)} · {e.amount}{e.perDay?'／天（有上限）':''}</p>)}<small>五件製作費：{set.cost.join(' + ')} 工藝碎片</small><button className="buy-button" disabled={t.sets.includes(i)||s.best<set.stage||t.shards<craftPrice(t,i)||!['Rare','Legendary','Mythic'].includes(set.rarity)||t.inventory.length>=100} onClick={()=>act({type:'craft',index:i})}>{s.best<set.stage?`第 ${set.stage} 關開放`:t.sets.includes(i)?'已完成':`製作缺少部位 · ${Number.isFinite(craftPrice(t,i))?craftPrice(t,i):'—'} 碎片`}</button></article>)}</>
  :collection==='achievements'?<><div className="content-heading"><h3>成就 {TT2_ACHIEVEMENTS.filter((_,i)=>achievementTier(s,i)>0).length} / {TT2_ACHIEVEMENTS.length}</h3><p>{ACHIEVEMENT_PANEL_TEXT.ACHIEVEMENT_PANEL_DESC}</p><p>💎{fmt(s.diamonds)} 鑽石 · 可領取 {TT2_ACHIEVEMENTS.reduce((n,_,i)=>n+achievementReward(s,i),0)} 鑽石</p></div>
  {TT2_ACHIEVEMENTS.map((a,i)=>{const blocked=UNMEASURED_ACHIEVEMENTS[a.type],tier=achievementTier(s,i),claimed=achievementClaimed(s,i),reward=achievementReward(s,i);
   const target=fromText(a.requirement[Math.min(tier,a.requirement.length-1)]),progress=achievementProgress(s,i);
   const share=blocked||tier>=a.requirement.length?tier>=a.requirement.length?1:0:Math.max(0,Math.min(1,ratio(progress,target)));
   return <article className="feature-card" key={a.type}>
    <h3>{a.description.replace('{0}',fmt(target))}<small>{blocked?'待實作':`第 ${tier} / ${a.requirement.length} 階`}</small></h3>
    {blocked?<p>{blocked}</p>:<><p>目前 {fmt(progress)} · 已領 {claimed} 階 · 本階獎勵 💎{a.diamondReward[Math.min(tier,a.diamondReward.length-1)]}</p>
    <div className="hp-track"><div style={{width:`${share*100}%`}}/></div>
    <button className="buy-button" disabled={!reward} onClick={()=>act({type:'achievement',index:i})}>{reward?`領取 💎${reward}`:tier>=a.requirement.length?'已全部領取':'尚未達成'}</button></>}
   </article>;})}
  <div className="content-heading"><h3>{ACHIEVEMENT_PANEL_TEXT.ACHIEVEMENTS_PANEL_DAILY_TITLE ?? '每日'}成就 {TT2_DAILY_TASKS.filter((_,i)=>dailyTaskClaimed(s,i)).length} / {TT2_DAILY_TASKS.filter((_,i)=>dailyTaskAvailable(i)).length}</h3><p>每日世界標準時間零時重置。</p></div>
  {TT2_DAILY_TASKS.map((d,i)=>{const blocked=!d.active?'安裝包把這項標為未啟用':UNMEASURED_DAILY_TASKS[d.type];
   const done=dailyTaskDone(s,i),claimed=dailyTaskClaimed(s,i),paid=d.rewards.filter(r=>DAILY_TASK_PAID.includes(r.reward as typeof DAILY_TASK_PAID[number]));
   return <article className="feature-card" key={d.type}>
    <h3>{d.description.replace('{0}',String(d.requirement))}<small>{blocked?'待實作':claimed?'已領取':`${dailyTaskProgress(s,i)} / ${d.requirement}`}</small></h3>
    {blocked?<p>{blocked}</p>:<><p>獎勵 {paid.map(r=>`${r.reward==='Diamonds'?'💎':'🎟'}${r.amount}`).join(' · ')}{paid.length<d.rewards.length?` · 另有 ${d.rewards.filter(r=>!paid.includes(r)).map(r=>r.reward).join('、')} 尚未開放`:''}</p>
    <button className="buy-button" disabled={!done||claimed} onClick={()=>act({type:'dailyTask',index:i})}>{claimed?ACHIEVEMENT_PANEL_TEXT.DAILY_ACHIEVEMENT_ALREADY_COLLECTED ?? '已領取':done?'領取':'尚未完成'}</button></>}
   </article>;})}
  <p className="panel-note">10 項每日成就取自安裝包 DailyAchievementInfo，敘述為官方繁體中文字串。其中 UniqueArtifacts 的 IsActive 欄為 FALSE，安裝包本身就未啟用；另有五項所依賴的系統尚未實作。獎勵字串同時列出突襲券、鍊金與寶石貨幣，這三種在本專案尚未存在，只發放鑽石與活動幣並在上方標明。</p>
  <p className="panel-note">22 項成就與各五階門檻、鑽石獎勵取自安裝包 AchievementInfo，敘述為安裝包官方繁體中文字串。原生列舉另有 ChestTokens 一項，安裝包的資料表沒有對應列，因此未列出。錦標賽與魔力瑪尼兩項所依賴的系統尚未實作，標為待實作且不可領取。</p></>
  :<><div className="content-heading"><h3>流派加成核對</h3><p>這是計算預覽。公會飛船、匕首與金槍完整戰鬥尚待還原；寵物基礎蓄力攻擊已開放。</p></div><div className="collection-tabs">{builds.map(([id,name])=><button key={id} className={selected===id?'chosen':''} onClick={()=>setSelected(id)}>{name}</button>)}</div><article className="feature-card"><h3>{builds.find(b=>b[0]===selected)?.[1]}</h3><p>點擊加成指數 {BUILD_COEFFICIENTS[selected].tap}</p><p>英雄加成指數 {BUILD_COEFFICIENTS[selected].hero}</p><p>目前預估傷害 {fmt(buildDamage(s,selected))}</p><p>例如點擊倍率 十的一百次方，影分身只取得 十的六十次方，飛船取得 ×1。</p></article></>}
 </>:tab==='shop'?<>
  <div className="content-heading"><h3>增益道具</h3><p>💎{fmt(s.diamonds)} 鑽石 · 登入兌換次數 {t.perkTokens}</p></div>
  {RESOURCE_PERKS.map((p,i)=>{const level=perkLevel(t,i,s.last),full=level>=perkLimit(t),ends=t.perkEnds[i].filter(end=>end>s.last).sort((a,b)=>a-b);return <article className="feature-card" key={p.id}><h3>{p.icon} {p.name}<small>{level} / {perkLimit(t)} 層</small></h3><p>{p.description}</p>{level>0&&<p>{i===0?`目前回復倍率 ×${perkValue(t,i,s.last)}`:`每 ${Number(perkValue(t,i,s.last).toFixed(2))} 秒自動升級`}</p>}{ends.map((end,j)=><p key={j}>第 {j+1} 層剩餘 {Math.ceil((end-s.last)/60000)} 分鐘</p>)}{full&&<p>層數已滿；再使用會把剩餘時間最短的那層換成完整十二小時。</p>}<div className="feature-actions"><button className="buy-button" disabled={s.diamonds<p.cost} onClick={()=>act({type:'resourcePerk',index:i})}>使用 · 💎{p.cost}</button><button className="outline-button" disabled={t.perkTokens<1} onClick={()=>act({type:'resourcePerk',index:i,amount:1})}>使用登入兌換次數</button></div></article>;})}
  <p className="panel-note">每層各計時十二小時，蛻變不重置。登入獎勵暫可自選這兩種增益；原版隨機配發、黃金雨立即金幣及離線自動升級仍待核實。</p>
  <div className="content-heading"><h3>每日登入</h3><p>💎{fmt(s.diamonds)} 鑽石 · ◆{fmt(s.relics)} 聖物 · {t.shards} 工藝碎片</p></div>
  <button className="buy-button" disabled={t.loginAt===Math.floor(s.last/86400000)} onClick={()=>act({type:'daily'})}>{t.loginAt===Math.floor(s.last/86400000)?'今日已領取':`領取第 ${t.loginIndex%14+1} 天`}</button>
  {TT2_DAILY.map((d,i)=><article className="feature-card" key={d.day}><h3>第 {d.day} 天 {i===t.loginIndex%14?'· 下次獎勵':''}</h3><p>{({MonsterGold:'普通泰坦金幣',Diamonds:'鑽石',Equipment:'裝備',Pet:'寵物等級',Perk:'增益兌換次數',EquipmentShards:'工藝碎片',HelperWeapon:'英雄武器',SkillPoint:'技能點'} as Record<string,string>)[d.reward]} ×{d.amount}</p></article>)}
  <p className="panel-note">依 7.5 的 14 日表循環，每日世界標準時間零時（臺灣時間上午八時） 重置。增益待領 {t.perkTokens} 次、活動幣 {t.eventCurrency} 已保留。增益可在上方兌換；活動商店尚未開放。</p>{s.log.map((x,i)=><p className="event-log" key={i}>{x}</p>)}
 </>:<div className="prestige-card"><div className="prestige-orb">✦</div><h2>蛻變</h2><p>最高第 60 關開放。重置金幣、當前關卡及英雄，保留神器、鑽石、技能樹與收藏。</p><div className="prestige-reward"><span>預計獲得聖物</span><strong>◆{fmt(relicGain(s))}</strong></div><button className="primary-button" disabled={s.best<60} onClick={onPrestige}>蛻變</button><p className="panel-note">紅書倍率已接上。基礎聖物曲線、進階起始關卡及里程碑尚未完整還原。</p></div>}
 </fieldset>;
}
