// Generated by tools/import-skill-names.py from the bundled Traditional Chinese file.
// Do not edit by hand; tests/name-parity.test.mjs checks every skill still has its text.
//
// flavour: what the skill is. quick: what it does, with {0} standing in for the multiplier
// the engine computes. secondary: the extra effect four of the six carry.
export type SkillText = { flavour: string; quick: string; secondary?: string };
export const SKILL_TEXT: Record<string, SkillText> = {
  "BurstDamage": {
    "flavour": "劍術大師引用神的力量對所有敵人放出爆炸性的傷害",
    "quick": "造成{0}倍點擊傷害",
    "secondary": "泰坦跳過: {0}"
  },
  "CritBoost": {
    "flavour": "劍術大師釋放潛在的能量來造成爆發性的傷害",
    "quick": "增加致命爆擊傷害 {0}x 倍",
    "secondary": "致命打擊機率：{0}"
  },
  "HandOfMidas": {
    "flavour": "劍術大師獲得神靈附體並被賦予大量黃金",
    "quick": "增加點擊與金幣壺的黃金量{0}倍"
  },
  "TapBoost": {
    "flavour": "劍術大師點燃他的寶劍，對敵人造成額外傷害",
    "quick": "點擊傷害增加{0}倍"
  },
  "HelperBoost": {
    "flavour": "英雄們聚集在你周圍，提升他們的傷害還有攻擊次數",
    "quick": "所有英雄傷害增加{0}倍",
    "secondary": "英雄攻擊速度：{0}倍"
  },
  "ShadowClone": {
    "flavour": "一位來自冥界的複製人將現身協助劍術大師戰鬥",
    "quick": "每秒造成{0}倍點擊傷害",
    "secondary": "每秒特殊行動嘗試次數：{0}"
  }
};
