"""Generate lib/tt2-stages.ts from the bundled background tables.

Which titan shows up on a stage is not a formula, it is two tables. BackgroundInfo lists, for each
of the 70 background levels, its theme, its stage boss and the ten monsters that belong to it.
BackgroundCycleInfo says how many of those ten are in play at a given stage and how large they are
drawn. The native rule that reads them is recorded in reference/tt2/8.2.0/stage-monster-evidence.json.

Run after changing the reference tables:  python tools/import-stage-monsters.py
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
REFERENCE = ROOT/'reference/tt2/8.2.0'


def records(table):
    return json.loads((REFERENCE/f'{table}.json').read_text(encoding='utf-8'))['records']


def main():
    levels = []
    for row in sorted(records('BackgroundInfo'), key=lambda r: int(r['values']['Level'])):
        values = row['values']
        levels.append({
            'level': int(values['Level']),
            'theme': values['Theme'],
            'boss': values['Boss'],
            'monsters': [values[f'Monster{i}'] for i in range(1, 11)],
        })
    if [entry['level'] for entry in levels] != list(range(1, len(levels)+1)):
        raise ValueError('BackgroundInfo levels are not a gapless 1..N run')

    cycle = []
    for row in sorted(records('BackgroundCycleInfo'), key=lambda r: int(r['values']['Level'])):
        values = row['values']
        cycle.append({
            'level': int(values['Level']),
            'themeEnd': int(values['ThemeEnd']),
            'diversity': int(values['MonsterDiversity']),
            'scale': float(values['Scale']),
        })
    if [entry['level'] for entry in cycle] != sorted(entry['level'] for entry in cycle):
        raise ValueError('BackgroundCycleInfo is not sorted by level')
    for entry in cycle:
        if not 1 <= entry['diversity'] <= 10:
            raise ValueError(f"diversity {entry['diversity']} outside the ten monster columns")

    names = sorted({name for entry in levels for name in entry['monsters']} | {entry['boss'] for entry in levels})

    # This project draws the monsters with its own sixty sprites, so 141 identifiers have to share
    # them. Numbering them in order would put two members of the same level on the same sprite far
    # more often than necessary, so the sprite is chosen by greedy colouring: ids that appear on a
    # level together are neighbours, and each id takes the lowest sprite none of its neighbours has.
    sprites = 60
    neighbours = {name: set() for name in names}
    for entry in levels:
        together = set(entry['monsters']) | {entry['boss']}
        for name in together:
            neighbours[name] |= together - {name}
    # Taking the lowest free sprite would satisfy the constraint with a dozen of them and leave the
    # rest of the art unused, so among the free ones take the least used so far: no level repeats a
    # sprite and all sixty stay in rotation.
    order = sorted(names, key=lambda name: (-len(neighbours[name]), name))
    sprite_of = {}
    used = [0]*sprites
    for name in order:
        taken = {sprite_of[other] for other in neighbours[name] if other in sprite_of}
        free = [s for s in range(sprites) if s not in taken] or list(range(sprites))
        choice = min(free, key=lambda s: (used[s], s))
        sprite_of[name] = choice
        used[choice] += 1
    clashes = sum(1 for entry in levels
                  for group in [[entry['boss'], *entry['monsters']]]
                  if len({sprite_of[name] for name in group}) < len(set(group)))
    if clashes:
        raise ValueError(f'{clashes} levels still draw two different monsters with one sprite')
    sprite_list = [sprite_of[name] for name in names]

    compact = json.dumps(levels, ensure_ascii=False, separators=(',', ':'))
    cycle_text = json.dumps(cycle, ensure_ascii=False, separators=(',', ':'))
    names_text = json.dumps(names, ensure_ascii=False, separators=(',', ':'))
    sprite_text = json.dumps(sprite_list, separators=(',', ':'))
    body = f'''// Generated by tools/import-stage-monsters.py from the bundled BackgroundInfo and
// BackgroundCycleInfo tables. Do not edit by hand; tests/stage-monsters.test.mjs re-derives both
// from reference/tt2/8.2.0 and fails if this file drifts.
//
// The names are the package's sprite identifiers, not display names: the original has no name for a
// stage titan, and the localization file carries none. This project draws them with its own art, so
// the identifier is what pins "the same creature", not what the player reads.

export type StageLevel = {{ level: number; theme: string; boss: string; monsters: string[] }};
export type BackgroundCycle = {{ level: number; themeEnd: number; diversity: number; scale: number }};

export const STAGE_LEVELS: StageLevel[] = {compact};

export const BACKGROUND_CYCLE: BackgroundCycle[] = {cycle_text};

/** Every monster identifier the tables use, as a stable sorted list. */
export const MONSTER_IDS: string[] = {names_text};

/** The sprite this project draws for MONSTER_IDS[i]; chosen so no level needs one sprite twice. */
export const MONSTER_SPRITES: number[] = {sprite_text};
'''
    target = ROOT/'lib/tt2-stages-data.ts'
    target.write_text(body, encoding='utf-8', newline='\n')
    print(f'Wrote {len(levels)} background levels, {len(cycle)} cycle rows, {len(names)} monster ids '
          f'over {len(set(sprite_list))} sprites, no level sharing one')


if __name__ == '__main__':
    main()
